using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace NoDestination {
public enum Journey { Moving, Arrived, Field, Remembered, Returned }
public sealed class MemoryTarget : MonoBehaviour { public string id; public string caption; }
public sealed class Prototype : MonoBehaviour {
 public Journey phase; public bool radioFound; public bool photoFound; public bool paused;
 public Camera eye; public CharacterController body;
 GameObject train, field, shortcut, door, extraSeat; Transform clockHand;
 AudioSource ambience; Material brass, wood, cream, green, dark, glass, wheat, plaster;
 readonly List<Transform> passingLights = new(); readonly Dictionary<string,MemoryTarget> targets = new();
 string subtitle="", prompt=""; float subtitleUntil, elapsed, pitch, footstep; bool testing;
 GUIStyle small, title, centered; Texture2D grain; float yaw;
 public static Prototype Instance;
 void Start(){ Instance=this; Build(); StartCoroutine(Arrival()); testing=Application.isEditor && System.IO.File.Exists("Artifacts/verify.request"); if(testing)StartCoroutine(Verify()); else Lock(true); }
 Material Mat(string name, Color color, bool unlit=false){var m=new Material(Shader.Find(unlit?"Universal Render Pipeline/Unlit":"Universal Render Pipeline/Lit"));m.name=name;m.color=color; if(!unlit){m.SetFloat("_Smoothness",.08f);var t=new Texture2D(32,32); var pixels=new Color[1024];var rng=new System.Random(name.GetHashCode());for(int i=0;i<pixels.Length;i++){float v=.8f+(float)rng.NextDouble()*.25f;pixels[i]=new Color(v,v,v);}t.SetPixels(pixels);t.Apply();t.filterMode=FilterMode.Point;t.wrapMode=TextureWrapMode.Repeat;m.mainTexture=t;m.mainTextureScale=new Vector2(2,2);}return m;}
 GameObject Box(string name,Vector3 pos,Vector3 size,Material mat,Transform parent=null,bool collider=true){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=name;g.transform.SetParent(parent,false);g.transform.localPosition=pos;g.transform.localScale=size;g.GetComponent<Renderer>().sharedMaterial=mat;if(!collider)Destroy(g.GetComponent<Collider>());return g;}
 void Label(string value,Vector3 pos,float scale,Transform parent,Quaternion rotation){var g=new GameObject(value);g.transform.SetParent(parent,false);g.transform.localPosition=pos;g.transform.localRotation=rotation;var t=g.AddComponent<TextMesh>();t.text=value;t.fontSize=64;t.characterSize=scale;t.anchor=TextAnchor.MiddleCenter;t.color=new Color(.89f,.78f,.54f);}
 void LightAt(Vector3 pos,Transform parent,Color color,float intensity,float range){var g=new GameObject("Warm pool of light");g.transform.SetParent(parent,false);g.transform.localPosition=pos;var l=g.AddComponent<Light>();l.type=LightType.Point;l.color=color;l.intensity=intensity;l.range=range;}
 void Target(GameObject g,string id,string caption){var t=g.AddComponent<MemoryTarget>();t.id=id;t.caption=caption;targets[id]=t;}
 void Seat(float x,float z,Transform root){Box("Velvet seat",new Vector3(x,.55f,z),new Vector3(1.35f,.25f,.75f),green,root);Box("Velvet back",new Vector3(x,1,z+.35f),new Vector3(1.35f,.85f,.15f),green,root);for(int s=-1;s<=1;s+=2){Box("Walnut armrest",new Vector3(x+s*.69f,.8f,z),new Vector3(.1f,.1f,.9f),wood,root);Box("Seat foot",new Vector3(x+s*.48f,.2f,z),new Vector3(.09f,.4f,.5f),brass,root);}}
 void Build(){
  UnityEngine.Random.InitState(317); Application.targetFrameRate=60;
  brass=Mat("Tarnished brass",new Color(.46f,.32f,.13f));wood=Mat("Walnut",new Color(.22f,.105f,.05f));cream=Mat("Aged ivory",new Color(.66f,.56f,.36f));green=Mat("Moss velvet",new Color(.16f,.23f,.17f));dark=Mat("Night",new Color(.025f,.035f,.039f),true);glass=Mat("Lamp glow",new Color(1,.7f,.3f),true);wheat=Mat("Ochre wheat",new Color(.64f,.43f,.13f));plaster=Mat("Faded plaster",new Color(.58f,.49f,.32f));
  RenderSettings.fog=true;RenderSettings.fogColor=new Color(.08f,.09f,.1f);RenderSettings.fogDensity=.024f;RenderSettings.ambientLight=new Color(.32f,.28f,.2f);RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Flat;RenderSettings.skybox=null;
  train=new GameObject("01 | NIGHT TRAIN");var tr=train.transform;
  Box("Carriage floor",new Vector3(0,-.15f,0),new Vector3(5,.3f,20),wood,tr);
  Box("Aisle runner",new Vector3(0,.012f,0),new Vector3(1.25f,.02f,19.7f),Mat("Oxide carpet",new Color(.3f,.12f,.09f)),tr);
  Box("Ceiling",new Vector3(0,3.15f,0),new Vector3(5,.25f,20),cream,tr);
  for(int side=-1;side<=1;side+=2){
   Box("Wainscot",new Vector3(side*2.5f,.5f,0),new Vector3(.16f,1,20),wood,tr);
   Box("Upper panel",new Vector3(side*2.5f,2.8f,0),new Vector3(.16f,.6f,20),cream,tr);
   Box("Window brass rail",new Vector3(side*2.4f,1.1f,0),new Vector3(.09f,.07f,20),brass,tr);
   for(int i=0;i<8;i++){float z=-8.75f+i*2.5f;Box("Window pillar",new Vector3(side*2.5f,1.8f,z-1.2f),new Vector3(.18f,1.5f,.2f),wood,tr);Box("Unmoving darkness",new Vector3(side*2.54f,1.8f,z),new Vector3(.08f,1.4f,2.3f),dark,tr);Seat(side*1.6f,z,tr);}
   Box("Luggage rack",new Vector3(side*1.95f,2.5f,0),new Vector3(.8f,.06f,18),brass,tr,false);
  }
  Box("Rear wall",new Vector3(0,1.5f,-10),new Vector3(5,3,.2f),wood,tr);var locked=Box("Car 0",new Vector3(0,1.25f,-9.85f),new Vector3(1.2f,2.5f,.1f),green,tr);Target(locked,"zero","E  /  EXAMINE");Label("0",new Vector3(0,1.8f,-9.77f),.13f,tr,Quaternion.Euler(0,180,0));
  for(int s=-1;s<=1;s+=2)Box("Vestibule wall",new Vector3(s*1.6f,1.5f,10),new Vector3(1.8f,3,.2f),wood,tr);
  door=Box("Sliding vestibule door",new Vector3(0,1.4f,10),new Vector3(1.4f,2.8f,.18f),green,tr);Target(door,"exit","E  /  STEP ONTO PLATFORM");Label("NO DESTINATION",new Vector3(0,2.8f,9.84f),.055f,tr,Quaternion.identity);
  for(int i=0;i<5;i++){float z=-8+i*4;Box("Ceiling lantern",new Vector3(0,2.92f,z),new Vector3(.5f,.15f,.7f),glass,tr,false);LightAt(new Vector3(0,2.65f,z),tr,new Color(1,.66f,.3f),2.8f,6);}
  var bag=Box("Unclaimed suitcase",new Vector3(1.6f,.89f,-3.75f),new Vector3(.75f,.48f,.32f),wood,tr);Target(bag,"bag","E  /  EXAMINE SUITCASE");Box("Suitcase handle",new Vector3(1.6f,1.2f,-3.75f),new Vector3(.28f,.07f,.06f),brass,tr);
  var ticket=Box("Red ticket",new Vector3(-1.6f,.69f,-6.3f),new Vector3(.3f,.03f,.16f),Mat("Ticket red",new Color(.7f,.08f,.055f)),tr);Target(ticket,"ticket","E  /  EXAMINE TICKET");
  Label("03:17",new Vector3(0,2.45f,9.82f),.07f,tr,Quaternion.identity);
  extraSeat=new GameObject("The seat that was not here");extraSeat.transform.SetParent(tr);Seat(0,-5,extraSeat.transform);extraSeat.SetActive(false);
  for(int side=-1;side<=1;side+=2)for(int i=0;i<5;i++)passingLights.Add(Box("Passing track light",new Vector3(side*2.48f,1.65f,-10+i*4),new Vector3(.015f,.035f,.25f),Mat("Distant amber "+side+" "+i,new Color(.23f,.16f,.07f),true),tr,false).transform);
  field=new GameObject("02 | THE FIELD");field.transform.position=new Vector3(100,0,0);var f=field.transform;
  Box("Endless earth",new Vector3(0,-.2f,35),new Vector3(220,.4f,240),wheat,f);
  Box("Footpath",new Vector3(0,.015f,20),new Vector3(2.8f,.025f,42),Mat("Dust",new Color(.52f,.4f,.23f)),f);
  Platform(f,new Vector3(0,0,0));
  var sun=new GameObject("Late afternoon that never ends");sun.transform.SetParent(f);sun.transform.rotation=Quaternion.Euler(23,-35,0);var dl=sun.AddComponent<Light>();dl.type=LightType.Directional;dl.color=new Color(1,.73f,.39f);dl.intensity=1.2f;
  MakeWheat(f);
  Box("House floor",new Vector3(0,.02f,45),new Vector3(9,.08f,10),wood,f);
  Box("House back",new Vector3(0,1.6f,50),new Vector3(9,3.2f,.2f),plaster,f);
  for(int s=-1;s<=1;s+=2){Box("House siding",new Vector3(s*4.5f,1.6f,45),new Vector3(.2f,3.2f,10),plaster,f);Box("Front wall",new Vector3(s*2.9f,1.6f,40),new Vector3(3.2f,3.2f,.2f),plaster,f);}
  Box("Door lintel",new Vector3(0,2.9f,40),new Vector3(2.6f,.6f,.2f),wood,f);
  for(int s=-1;s<=1;s+=2){var roof=Box("Pitched roof",new Vector3(s*2.4f,3.95f,45),new Vector3(5.4f,.22f,11),wood,f);roof.transform.localRotation=Quaternion.Euler(0,0,s*-20);}
  Box("Table",new Vector3(-1.8f,.9f,46),new Vector3(2.1f,.16f,1.1f),wood,f);for(int s=-1;s<=1;s+=2)Box("Table leg",new Vector3(-1.8f+s*.85f,.45f,46),new Vector3(.12f,.9f,.8f),wood,f);
  var radio=Box("Radio",new Vector3(-1.8f,1.3f,46),new Vector3(1,.65f,.42f),wood,f);Target(radio,"radio","E  /  TURN ON RADIO");Box("Radio grille",new Vector3(-1.9f,1.3f,45.77f),new Vector3(.65f,.45f,.02f),brass,f,false);Label("AM  0317",new Vector3(-1.8f,1.5f,45.74f),.022f,f,Quaternion.identity);
  var photo=Box("Family photograph",new Vector3(1.6f,1.8f,49.8f),new Vector3(1.4f,1.1f,.12f),wood,f);Target(photo,"photo","E  /  EXAMINE FAMILY PHOTOGRAPH");Box("Faded photo paper",new Vector3(1.6f,1.8f,49.72f),new Vector3(1.18f,.88f,.02f),cream,f,false);
  for(int i=0;i<3;i++){float x=1.2f+i*.4f;Box("Indistinct figure",new Vector3(x,1.63f,49.69f),new Vector3(.24f,i==1?.3f:.44f,.015f),green,f,false);Box("Erased face",new Vector3(x,i==1?1.93f:2.02f,49.67f),new Vector3(.2f,.2f,.02f),plaster,f,false);}
  LightAt(new Vector3(0,2.7f,45),f,new Color(1,.73f,.42f),4,12);
  shortcut=new GameObject("Impossible platform");shortcut.transform.SetParent(f,false);Platform(shortcut.transform,new Vector3(0,.05f,37));shortcut.SetActive(false);
  field.SetActive(false);
  var player=new GameObject("Player | WASD Mouse E");body=player.AddComponent<CharacterController>();body.height=1.75f;body.radius=.24f;body.center=new Vector3(0,.88f,0);body.stepOffset=.25f;player.transform.position=new Vector3(0,.12f,-7);
  var cam=new GameObject("Eyes");cam.transform.SetParent(player.transform,false);cam.transform.localPosition=new Vector3(0,1.6f,0);eye=cam.AddComponent<Camera>();eye.nearClipPlane=.05f;eye.farClipPlane=150;eye.fieldOfView=68;eye.clearFlags=CameraClearFlags.SolidColor;eye.backgroundColor=RenderSettings.fogColor;cam.tag="MainCamera";cam.AddComponent<AudioListener>();
  ambience=player.AddComponent<AudioSource>();ambience.loop=true;ambience.clip=Sound(false,8);ambience.volume=.18f;ambience.Play();
  grain=new Texture2D(128,128);var px=new Color[128*128];for(int i=0;i<px.Length;i++)px[i]=new Color(0,0,0,UnityEngine.Random.value*.12f);grain.SetPixels(px);grain.Apply();grain.filterMode=FilterMode.Point;
 }
 void Platform(Transform p,Vector3 o){Box("Carriage exterior",o+new Vector3(0,1.6f,-2.7f),new Vector3(13,3.2f,.35f),wood,p);for(int side=-1;side<=1;side+=2)for(int i=1;i<=3;i++)Box("Exterior window",o+new Vector3(side*i*1.8f,1.8f,-2.49f),new Vector3(1.3f,.9f,.02f),dark,p);Label("THE FIELD",o+new Vector3(2.6f,2.7f,.07f),.065f,p,Quaternion.Euler(0,180,0));Box("Platform",o+new Vector3(0,.04f,0),new Vector3(7,.08f,5),plaster,p);Box("Platform edge",o+new Vector3(0,.1f,-2.3f),new Vector3(7,.04f,.16f),cream,p);Box("Station post",o+new Vector3(2.6f,1.6f,0),new Vector3(.13f,3.2f,.13f),wood,p);Box("Station sign",o+new Vector3(2.6f,2.7f,0),new Vector3(2,.6f,.12f),green,p);var ret=Box("Waiting train doorway",o+new Vector3(0,1.3f,-2.25f),new Vector3(1.7f,2.6f,.18f),green,p);Target(ret,p==shortcut?.transform?"returnNear":"return","E  /  RETURN TO TRAIN");}
 void MakeWheat(Transform parent){var verts=new List<Vector3>();var tris=new List<int>();var rng=new System.Random(317);for(int i=0;i<24000;i++){float x=(float)rng.NextDouble()*160-80,z=(float)rng.NextDouble()*165-45;if(Mathf.Abs(x)<2&&z<41&&z>-4||Mathf.Abs(x)<5.5f&&z>39&&z<51||Mathf.Abs(x)<5&&z>-4&&z<4)continue;float h=.6f+(float)rng.NextDouble()*.6f;int k=verts.Count;verts.Add(new Vector3(x-.07f,0,z));verts.Add(new Vector3(x+.07f,0,z));verts.Add(new Vector3(x+.035f,h+.13f,z));verts.Add(new Vector3(x-.025f,h,z));tris.AddRange(new[]{k,k+2,k+1,k,k+3,k+2,k+1,k+2,k,k+2,k+3,k});}var mesh=new Mesh();mesh.indexFormat=UnityEngine.Rendering.IndexFormat.UInt32;mesh.SetVertices(verts);mesh.SetTriangles(tris,0);var normals=new Vector3[verts.Count];for(int i=0;i<normals.Length;i++)normals[i]=Vector3.up;mesh.normals=normals;var g=new GameObject("Wheat | combined low-poly mesh");g.transform.SetParent(parent,false);g.AddComponent<MeshFilter>().sharedMesh=mesh;g.AddComponent<MeshRenderer>().sharedMaterial=wheat;}
 AudioClip Sound(bool horn,float seconds){int rate=22050;var data=new float[(int)(rate*seconds)];var rng=new System.Random(317);for(int i=0;i<data.Length;i++){float t=(float)i/rate;data[i]=horn?(Mathf.Sin(t*207*6.283f)+Mathf.Sin(t*277*6.283f))*.12f*Mathf.Sin(Mathf.PI*t/seconds):((float)rng.NextDouble()*2-1)*.11f+Mathf.Sin(t*48*6.283f)*.06f+Mathf.Exp(-((t*2)%1)*24)*.12f;}var clip=AudioClip.Create(horn?"Distant horn":"Rail and wind",data.Length,1,rate,false);clip.SetData(data,0);return clip;}
 IEnumerator Arrival(){Say("This train has no destination.",5);yield return new WaitForSeconds(6);Say("Next stop...\n[static]",5);ambience.PlayOneShot(Sound(true,2),.4f);yield return new WaitForSeconds(5);phase=Journey.Arrived;door.transform.localPosition+=Vector3.right*1.05f;Say("THE FIELD\nE at the open vestibule to leave",6);Debug.Log("ND: Arrived");}
 void Lock(bool locked){Cursor.lockState=locked?CursorLockMode.Locked:CursorLockMode.None;Cursor.visible=!locked;}
 void Say(string s,float duration=5){subtitle=s;subtitleUntil=Time.time+duration;}
 public void Warp(Vector3 p,float angle){body.enabled=false;body.transform.position=p;body.transform.rotation=Quaternion.Euler(0,angle,0);body.enabled=true;yaw=angle;pitch=0;eye.transform.localRotation=Quaternion.identity;}
 void Update(){if(eye==null)return;if(!paused&&(phase==Journey.Moving||phase==Journey.Returned)){foreach(var lamp in passingLights){var p=lamp.localPosition;p.z-=Time.deltaTime*8;if(p.z< -10)p.z+=20;lamp.localPosition=p;}}if(Input.GetKeyDown(KeyCode.Escape)){paused=!paused;Time.timeScale=paused?0:1;Lock(!paused&&!testing);}if(paused||testing)return;float dt=Mathf.Min(Time.deltaTime,.05f);yaw+=Input.GetAxisRaw("Mouse X")*1.7f;pitch=Mathf.Clamp(pitch-Input.GetAxisRaw("Mouse Y")*1.7f,-80,80);body.transform.rotation=Quaternion.Euler(0,yaw,0);eye.transform.localRotation=Quaternion.Euler(pitch,0,0);var move=Vector3.ClampMagnitude(new Vector3(Input.GetAxisRaw("Horizontal"),0,Input.GetAxisRaw("Vertical")),1);body.Move((body.transform.TransformDirection(move)*(Input.GetKey(KeyCode.LeftShift)?4.6f:2.8f)+Vector3.down*3)*dt);prompt="";if(Physics.Raycast(eye.transform.position,eye.transform.forward,out var hit,3)){var target=hit.collider.GetComponent<MemoryTarget>();if(target!=null){prompt=target.caption;if(Input.GetKeyDown(KeyCode.E))Interact(target.id);}}if(phase==Journey.Arrived&&body.transform.position.z>9){prompt="E  /  STEP ONTO PLATFORM";if(Input.GetKeyDown(KeyCode.E))Interact("exit");}if(body.transform.position.y < -5)Warp(phase>=Journey.Field&&phase<Journey.Returned?new Vector3(100,.15f,1):new Vector3(0,.15f,7),0);}
 public void Interact(string id){switch(id){case "exit":if(phase!=Journey.Arrived){Say("The door will open when it is time.");return;}phase=Journey.Field;train.SetActive(false);field.SetActive(true);RenderSettings.fogColor=new Color(.66f,.52f,.31f);RenderSettings.fogDensity=.018f;eye.backgroundColor=RenderSettings.fogColor;ambience.volume=.07f;Warp(new Vector3(100,.15f,1),0);Say("THE FIELD\nThe sun has not moved.");break;case "radio":radioFound=true;Say("Next stop...\nYou have been here before.",7);ambience.PlayOneShot(Sound(false,2),.6f);break;case "photo":if(photoFound){Say("You cannot remember their faces.");break;}photoFound=true;phase=Journey.Remembered;shortcut.SetActive(true);Say("You cannot remember their faces.",5);ambience.PlayOneShot(Sound(true,4),.6f);break;case "return":case "returnNear":if(!photoFound){Say("There is a house beyond the wheat.");return;}phase=Journey.Returned;field.SetActive(false);train.SetActive(true);door.transform.localPosition=new Vector3(0,1.4f,10);extraSeat.SetActive(true);targets["bag"].gameObject.SetActive(false);RenderSettings.fogColor=new Color(.08f,.09f,.1f);eye.backgroundColor=RenderSettings.fogColor;ambience.volume=.18f;Warp(new Vector3(0,.15f,7.8f),180);Say("Next stop...\n...",7);break;case "bag":Say("No name. No weight.\nIt feels like yours.");break;case "ticket":Say("UNKNOWN  →  HOME\nThe destination has been crossed out.");break;case "zero":Say("0\nNot yet.");break;}Debug.Log("ND: "+id+" -> "+phase);}
 void OnGUI(){if(eye==null)return;if(small==null){small=new GUIStyle(GUI.skin.label){fontSize=16,normal={textColor=new Color(.88f,.82f,.67f)}};centered=new GUIStyle(small){alignment=TextAnchor.MiddleCenter};title=new GUIStyle(centered){fontSize=32};}GUI.DrawTexture(new Rect(0,0,Screen.width,Screen.height),grain,ScaleMode.StretchToFill,true);GUI.Label(new Rect(30,22,420,25),"NO DESTINATION   /   01",small);GUI.Label(new Rect(30,Screen.height-38,650,25),"WASD  walk     MOUSE  look     E  examine     SHIFT  hurry     ESC  pause",small);GUI.Label(new Rect(Screen.width/2-4,Screen.height/2-12,12,24),"·",centered);if(Time.time<subtitleUntil)GUI.Label(new Rect(Screen.width/2-320,Screen.height-145,640,80),subtitle,centered);GUI.Label(new Rect(Screen.width/2-260,Screen.height/2+28,520,35),prompt,centered);if(paused){GUI.Box(new Rect(Screen.width/2-230,Screen.height/2-140,460,280),"");GUI.Label(new Rect(Screen.width/2-220,Screen.height/2-120,440,55),"NO DESTINATION",title);if(GUI.Button(new Rect(Screen.width/2-120,Screen.height/2-30,240,40),"RESUME")){paused=false;Time.timeScale=1;Lock(true);}if(GUI.Button(new Rect(Screen.width/2-120,Screen.height/2+20,240,40),"RESTART THE JOURNEY")){Lock(false);Restart();}if(GUI.Button(new Rect(Screen.width/2-120,Screen.height/2+70,240,40),"QUIT"))Application.Quit();}}
 IEnumerator Verify(){yield return new WaitForSeconds(9);ScreenCapture.CaptureScreenshot("Artifacts/01-train.png");yield return new WaitForSeconds(4);Require(phase==Journey.Arrived,"arrival");yield return WalkTo(new Vector3(0,.15f,8));Require(body.transform.position.z>7.5f,"carriage aisle collision traversal");Interact("exit");yield return new WaitForSeconds(2);ScreenCapture.CaptureScreenshot("Artifacts/02-field.png");yield return new WaitForEndOfFrame();yield return null;Require(phase==Journey.Field,"field");yield return WalkTo(new Vector3(100,.15f,43));Require(body.transform.position.z>42.5f,"field path and house doorway traversal");Warp(new Vector3(98.2f,.15f,44),0);yield return null;Require(Physics.Raycast(eye.transform.position,(targets["radio"].transform.position-eye.transform.position).normalized,out var r,3)&&r.collider.GetComponent<MemoryTarget>()?.id=="radio","radio reachable");Interact("radio");Warp(new Vector3(101.6f,.15f,47.5f),0);Interact("photo");yield return new WaitForSeconds(2);ScreenCapture.CaptureScreenshot("Artifacts/03-memory.png");yield return new WaitForEndOfFrame();yield return null;Require(shortcut.activeSelf&&photoFound&&radioFound,"memory and anomaly");Warp(new Vector3(100,.15f,41),180);yield return new WaitForSeconds(2);ScreenCapture.CaptureScreenshot("Artifacts/04-impossible-platform.png");yield return new WaitForEndOfFrame();yield return null;Interact("returnNear");yield return new WaitForSeconds(2);ScreenCapture.CaptureScreenshot("Artifacts/05-return.png");Require(phase==Journey.Returned&&extraSeat.activeSelf&&!targets["bag"].gameObject.activeSelf,"return mutation");System.IO.File.WriteAllText("Artifacts/verification.txt","PASS: timed arrival, field entry, radio line of sight, radio memory, photograph, impossible platform, train return, added seat and missing suitcase.\nRuntime assertions; scripted walkthrough, not manual input testing.");Debug.Log("ND: VERIFICATION PASS");}
 IEnumerator WalkTo(Vector3 destination){float timeout=Time.time+20;while(Vector3.Distance(new Vector3(body.transform.position.x,0,body.transform.position.z),new Vector3(destination.x,0,destination.z))>.15f&&Time.time<timeout){var d=destination-body.transform.position;d.y=0;body.Move((d.normalized*5+Vector3.down*3)*Mathf.Min(Time.deltaTime,.04f));yield return null;}}
 void Require(bool condition,string name){if(!condition)throw new Exception("ND verification failed: "+name);Debug.Log("ND CHECK: "+name);}
 void Restart(){Time.timeScale=1;
#if UNITY_EDITOR
 UnityEditor.SceneManagement.EditorSceneManager.LoadSceneInPlayMode(SceneManager.GetActiveScene().path,new LoadSceneParameters(LoadSceneMode.Single));
#else
 SceneManager.LoadScene(0);
#endif
 }
 void OnDestroy(){Time.timeScale=1;Lock(false);}
}
}





